# Generated by Django 6.0.4 on 2026-07-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("name", models.CharField(max_length=20)),
                ("roll_no", models.IntegerField(blank=True, null=True)),
                ("image", models.ImageField(null=True, upload_to="images/")),
            ],
        ),
    ]
